services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/extra-filesystems/sda2:ro
      - /home:/extra-filesystems/sda6:ro
    environment:
      LISTEN: 45876
      KEY: $BESZEL_KEY
  certbot:
    container_name: certbot
    image: certbot/dns-cloudflare

    # Dry Run
    # command: certonly --non-interactive --dns-cloudflare --dns-cloudflare-credentials /run/secrets/cf_credentials --agree-tos --email $ADMIN_EMAIL -d *.$ROOT_DOMAIN --server https://acme-v02.api.letsencrypt.org/directory --dry-run

    # Issue certificate
    # command: certonly --non-interactive --dns-cloudflare --dns-cloudflare-credentials /run/secrets/cf_credentials --agree-tos --email $ADMIN_EMAIL -d *.$ROOT_DOMAIN --server https://acme-v02.api.letsencrypt.org/directory

    # Renew certificate
    command: renew --non-interactive --no-self-upgrade --dns-cloudflare --dns-cloudflare-credentials /run/secrets/cf_credentials --agree-tos --email $ADMIN_EMAIL --server https://acme-v02.api.letsencrypt.org/directory

    volumes:
      - ./certs/:/etc/letsencrypt
      - ./letsencrypt/log:/var/log/letsencrypt
    secrets:
      - cf_credentials

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    shm_size: '256m'
    ports:
      - "2424:22"
      - "80:80"
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '$GITLAB_URL'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['lfs_enabled'] = true
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    networks:
      - frontend
    restart: unless-stopped

secrets:
  cf_credentials:
    file: ./cloudflare/credentials
